add_library(freertos 
    STATIC
    ${CMAKE_CURRENT_SOURCE_DIR}/portable/GCC/ARM_CM0/mpu_wrappers_v2_asm.c
    ${CMAKE_CURRENT_SOURCE_DIR}/portable/GCC/ARM_CM0/port.c
    ${CMAKE_CURRENT_SOURCE_DIR}/portable/GCC/ARM_CM0/portasm.c
    ${CMAKE_CURRENT_SOURCE_DIR}/portable/MemMang/heap_4.c
    ${CMAKE_CURRENT_SOURCE_DIR}/event_groups.c
    ${CMAKE_CURRENT_SOURCE_DIR}/list.c
    ${CMAKE_CURRENT_SOURCE_DIR}/queue.c
    ${CMAKE_CURRENT_SOURCE_DIR}/stream_buffer.c
    ${CMAKE_CURRENT_SOURCE_DIR}/tasks.c
    ${CMAKE_CURRENT_SOURCE_DIR}/timers.c
)

target_include_directories(freertos
    PUBLIC
    ${CORE_INC}
    ${CMSIS_INC}
    ${DEVICE_INC}
    ${FREERTOS_INC}
    ${FREERTOS_ARM_INC}
)
